CREATE DATABASE IF NOT EXISTS powerfit CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE powerfit;

CREATE TABLE IF NOT EXISTS alunos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    telefone VARCHAR(20) NOT NULL,
    senha VARCHAR(255) NOT NULL
);
